server:
  port: 8080


spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/board
      username: root
      password: 1151

mybatis:
  configuration:
    map-underscore-to-camel-case: true


